### ISSUE TITLE
Documentation for each plugin's options

### ISSUE THREAD

**Issue by flexibeast** [WayfireWM/wayfire-plugins-extra#200]
The attached file, [wpe-options.md](https://github.com/WayfireWM/wayfire-plugins-extra/files/12865377/wpe-options.md), based on the format/style of [the 'Configuration' page on the Wayfire wiki](https://github.com/WayfireWM/wayfire/wiki/Configuration), documents the options available for each plugin, and is suitable for being copy-pasted into a page of a wiki in this repo, were one to be created.

There are two `TODO` items:

* i don't understand the `transparent_behind_views` option for the `force-fullscreen` plugin, despite looking at the relevant source (i'm new to Wayland).
* i don't understand the purpose of the `keycolor` plugin at all (although i can see the effect the latter has on my desktop, in terms of how it changes the presentation of text).

**Comment by soreau** [comment]
> The attached file, [wpe-options.md](https://github.com/WayfireWM/wayfire-plugins-extra/files/12865377/wpe-options.md), based on the format/style of [the 'Configuration' page on the Wayfire wiki](https://github.com/WayfireWM/wayfire/wiki/Configuration), documents the options available for each plugin, and is suitable for being copy-pasted into a page of a wiki in this repo, were one to be created.
> 

@flexibeast Thank you for your contribution, this is something that I have neglected as maintainer of this repository, but mostly because I'm not the greatest at making decent documentation. I do believe the wiki here is open and editable by anyone. If this is not the case, please let me know. To get started, simply click on the wiki button and start creating pages.

> There are two `TODO` items:
> 
>     * i don't understand the `transparent_behind_views` option for the `force-fullscreen` plugin, despite looking at the relevant source (i'm new to Wayland).
> 

The transparent-behind-views option is for windows that are semi-transparent (such as some terminals) or made semi-transparent with the alpha plugin. If this option is enabled, you can see through to the desktop in this case. If it is disabled, the plugin will render black behind the semi-transparent, and not show the desktop through the semi-transparent portions of the window. I did some work in this area recently, so make sure you have latest wayfire-plugins-extra to test with wayfire 0.8.x.

>     * i don't understand the purpose of the `keycolor` plugin at all (although i can see the effect the latter has on my desktop, in terms of how it changes the presentation of text).

The keycolor plugin is a demonstration of how to render each window with a different shader. Currently, it affects all windows the same, but this can be changed in the code or by writing a new plugin altogether, based on keycolor. The options are as follows: The color option is the pixels in the window to be replaced with alpha. The opacity is how much alpha to use. The threshold is how 'close' to the color to affect, i.e. it doesn't have to perfectly match. The range is 0-1, 0 meaning an exact pixel color match and 1 means any color will match. Yes, I understand there is no documentation and the plugin serves little purpose on it's own, but there are some people that do use it.

I hope this helps, and thanks for your work!

**Comment by soreau** [comment]
@flexibeast We want to put your wiki for wayfire-plugins-extra on this repo, not wayfire. We'll have to see if @ammen99 can enable the wiki here. I can see the button, but apparently it's not public.

**Comment by soreau** [comment]
@flexibeast We've made it so you should be able to edit the wiki now. Again, please let us know if this is not the case.

**Comment by flexibeast** [comment]
@soreau i've now successfully created the "Configuration" page on the wiki. Thanks! Closing.

**Comment by soreau** [comment]
@flexibeast Great work, thank you!
