### ISSUE TITLE
Can't terminate wayfire via kill -15 with glib-main-loop enabled

### ISSUE THREAD

**Issue by ssfdust** [WayfireWM/wayfire-plugins-extra#240]
**Describe the bug**
With glib-main-loop enabled, we can't kill wayfire. Wayfire is still running and doesn't print any shutdown information.

**To Reproduce**
1. Enable plugin glib-main-loop
2. killall wayfire or ctrl-c
3. It still runs

**Expected behavior**
Wayfire shutdowns

**Screenshots or stacktrace**
If it is a crash, attach the backtrace (or the whole log file), Wayfire will print it in the end of the log file or stdout.
Backtrace with address sanitizer enabled (if possible):

**Wayfire version**
latest git

**Comment by ammen99** [comment]
Actually, glib-main-loop already does that, however, the problem is that the shutdown signal is emitted from inside a signal handler, so wayfire probably gets stuck in some weird race condition. glib-main-loop somehow needs to signal to glib that the main loop should be terminated and not directly flush all wayland stuff and then exit(0)

**Comment by ssfdust** [comment]
Is there any plan to fix ths issue, 0.9 or 0.10?

**Comment by ammen99** [comment]
It is not very high on my list of priorities, feel free to send a PR.

**Comment by ssfdust** [comment]
The SIGTERM is always caught by the signal_handler function, it tries to shutdown the core but seems to be failed, the console does'nt print any errors. And the codes from glib-main-loop which connects to the shutdown signal are never executed.
I have no idea what can I do next, do you have any advice?

**Comment by ammen99** [comment]
> And the codes from glib-main-loop which connects to the shutdown signal are never executed.

That's quite weird, I would try to figure out why this is the case. Is the plugin using the wrong signal? The signal was not correctly emitted from core?

**Comment by ssfdust** [comment]
> Is the plugin using the wrong signal? The signal was not correctly emitted from core?
I set a breakpoint at the `wf::compositor_core_impl_t::fini` function, but it doesn't run.

**Comment by ammen99** [comment]
Ohhh, I see, we changed the order of signals in core because what we had previously was resulting in a deadlock sometimes.

We could probably use glib to handle the SIGINT and SIGTERM signals in the glib-main-loop plugin, thus overriding the handlers in main.cpp. Then glib-main-loop can stop both the glib loop and call `wl_display_terminate`.
