### ISSUE TITLE
[Feature] Themeable window decorations

### ISSUE THREAD

**Issue by pkillnine** [WayfireWM/wayfire-plugins-extra#51]
The decoration plugin provides window decoration. Making window decorations theme-able would be sweet, so I'm opening this issue in case anyone is interested.

**Comment by florhizome** [comment]
this is already included in  windecor, right?

**Comment by WammKD** [comment]
The `decoration` plugin certainly covers some elements, I'd think. But it does miss things like being able to set the font color (at least, from any documentation I was able to find though I may've missed somewhere).

Other common window decoration customizations are being able to set the border color and doing a vertical gradient for the title color.

I'd imagine, with those, you'd be able to get the decorations reasonably within throwing distance of whatever theme you might be using for GTK or QT.

**Comment by marcusbritanicus** [comment]
@WammKD with windecor you can set font color, family and size. Border color is currently same as titlebar colour. May be we can add few more options in windecor, I'm open to the idea. 

However, it's not possible to use Qt to perform the decorations - QApplication needs to be constructed in the app's (wayfire's) primary thread, and can't be done in a plugin. I'm not very sure if it's possible to use Gtk to do this - since I've never used it at all. 

Once transactions api land, I think it will be possible to write a decorator app, which means, we can write a Qt app to draw the decorations. Right, @ammen99 ?

**Comment by WammKD** [comment]
Oh, I wasn't saying to use GTK or QT to do so (I, actually, just figured you'd had reasons not to've done so, in the first place); I was more saying that, with those configure options, you'd be able to _match_ (make your decorations blend in with) whatever GTK or QT theme you were using; so that the decorations looked similar enough to the rest of the GTK or QT window, not that it was made with GTK or QT. Sorry about the confusion.

How does one set the font color and size? The documentation just says, "Sets the font to use for the title bars. The default is `sans-serif`," for `decoration.font`; I tried "Cantarell 50" just to see if, say, size was just supposed to be passed with the font name but it didn't seem to have any effect, at all. There didn't seem to be any specific `font_size` or the like that I could find, anywhere.

**Comment by marcusbritanicus** [comment]
@WammKD getting the decorations to match Gtk/Qt would mean trying to read their settings - especially the colour palettes. That's nearly impossible for a random program (or wayfire plugin) to do. Besides, how will you know which view is built using what toolkit? There can also be windows that are drawn using other toolkits. 

As for SSD of Wayfire, there are two different plugins: decoration (inbuilt) and windecor (a subproject of this repo). Font size and color can be set for windecor. You'll not find documentation for it in the wiki because it's a third-party plugin (and I've not yet written documentation for it 😝 )

[This](https://gitlab.com/wayfireplugins/windecor/-/blob/main/windecor.xml) XML file will give you the details you're looking for. You'll need to make a section `[windecor]` under which you can add the options. Alternatively, you can use wcm (wayfire configuration manager).

Do join us on [Matrix](https://matrix.to/#/#wayfire:matrix.org?via=matrix.org) or [IRC](https://web.libera.chat/#wayfire). It's awkward to have conversations via issue comments...

**Comment by AhoyISki** [comment]
In case anyone is still looking at this issue, I've Made a sophisticated [decoration plugin](https://github.com/AhoyISki/wayfire-firedecor) that let's you put decorations wherever you want, has outlines, customizable colors for the title, multiple themes depending on the window, and a lot more. 
So if you want to check it out, that'd be cool I guess.

**Comment by marcusbritanicus** [comment]
@AhoyISki nice work...!!

Regarding the themable icons, are they supposed to be drawn inside of the circles, or will they replace the circles?

**Comment by AhoyISki** [comment]
> @AhoyISki nice work...!!
> 
> Regarding the themable icons, are they supposed to be drawn inside of the circles, or will they replace the circles? 

What circles? Can you share a screenshot? Do you mean the themeable buttons?
